import { negotiationDataType } from "@/types/common";

export const handlerMappingConst = Object.freeze({
  RoleHandler: "tech_task.Offer",
  SingleHandler: "order.Order",
});

export const negotiationDataConst: negotiationDataType = Object.freeze({
  chain: {
    items: [],
  },
});

export const managerNegotiationChangeItemsConst = Object.freeze([
  "vat",
  "duty",
  "group",
  "okpd2",
  "price",
  "comment",
  "title",
  "tnved",
  "and_or",
  "excise",
  "item_size",
  "group_width",
  "piece_width",
  "duty_special",
  "group_height",
  "group_length",
  "pallet_count",
  "piece_height",
  "piece_length",
  "weight_gross",
  "packing_label",
  "price_segment",
  "alcohol_degree",
  "piece_volume_l",
  "excise_currency",
  "piece_weight_dry",
  "container_20_count",
  "container_40_count",
  "packing_group_type",
  "piece_packing_type",
  "source_description",
  "nesting_group_count",
  "pre_order_min_party",
  "transport_box_width",
  "transport_box_height",
  "transport_box_length",
  "transport_box_volume",
  "duty_special_currency",
  "excise_unit_measurement",
  "pre_order_quantity_pieces",
  "nesting_transport_box_count",
  "duty_special_unit_measurement",
  "piece_weight_net_with_packing",
]);

export const companyNegotiationChangeItemsConst = Object.freeze([
  "vat",
  "duty",
  "group",
  "okpd2",
  "price",
  "title",
  "tnved",
  "and_or",
  "excise",
  "item_size",
  "group_width",
  "piece_width",
  "duty_special",
  "group_height",
  "group_length",
  "pallet_count",
  "piece_height",
  "piece_length",
  "weight_gross",
  "packing_label",
  "price_segment",
  "alcohol_degree",
  "piece_volume_l",
  "excise_currency",
  "piece_weight_dry",
  "comment",
  "container_20_count",
  "container_40_count",
  "packing_group_type",
  "piece_packing_type",
  "source_description",
  "nesting_group_count",
  "pre_order_min_party",
  "transport_box_width",
  "transport_box_height",
  "transport_box_length",
  "transport_box_volume",
  "duty_special_currency",
  "excise_unit_measurement",
  "pre_order_quantity_pieces",
  "nesting_transport_box_count",
  "duty_special_unit_measurement",
  "piece_weight_net_with_packing",
]);

export const chainItemsFilterPresetConst = Object.freeze([
  "id",
  "title",
  "photo",
  "price",
  "currency",
  "source_description",
  "comment",
]);
